import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Raleway } from "next/font/google";
import AppLayout from "@/components/layout/AppLayout";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "Pansus Studio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("scroll-smooth font-sans", raleway.variable)}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
